version: "3.7"
services:
  client:
    container_name: mockme_client
    build: ./client
    expose:
      - 3001
    ports:
      - 3001:3000
    volumes:
      - ./client:/client
      - ./client/node_modules:/client/node_modules
    stdin_open: true
  server:
    container_name: mockme_server
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/server
      - ./server/node_modules:/server/node_modules
  redis-server:
    container_name: mockme_redis
    image: redis
    command: redis-server
    volumes:
      - ./data:/data
