version: "3.7"
services:
  client:
    build: ./client
    expose:
      - 3001
    ports:
      - 3001:3000
    volumes:
      - ./client:/client
      - /client/node_modules
    stdin_open: true
  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/server
      - /server/node_modules
  redis-server:
    image: redis
    command: redis-server
    volumes:
      - ./data:/data
